"""add password

Revision ID: 78899d2fe1d0
Revises: 7a3acf28f13d
Create Date: 2022-08-12 09:58:02.066650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78899d2fe1d0'
down_revision = '7a3acf28f13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('password', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'password')
    # ### end Alembic commands ###
