"""update

Revision ID: 7a3acf28f13d
Revises: b71cf009964a
Create Date: 2022-08-10 13:19:35.430879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a3acf28f13d'
down_revision = 'b71cf009964a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('devices', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('devices', sa.Column('is_delete', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_delete')
    op.drop_column('devices', 'is_active')
    op.alter_column('customer', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
