"""init

Revision ID: b71cf009964a
Revises: 
Create Date: 2022-08-10 11:28:49.236763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b71cf009964a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'NONE', name='customergender'), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('group', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_customer_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('devices')
    # ### end Alembic commands ###
